### ISSUE TITLE
HTML 수정해주세요

### ISSUE THREAD

**Issue by sigmadream** [byte7890/ks-web#1]
HTML 수정해주세요

**Comment by byte7890** [comment]
수정하고 다시 올리는걸 깜빡했네요.. 수정완료했습니다!
확인해주셔서 감사합니다!

나의 iPhone에서 보냄

**Comment by sigmadream** [comment]
감사합니다!

2020년 4월 11일 (토) 오전 1:24, 2015542105 <notifications@github.com>님이 작성:
